# -*- coding: utf-8 -*-
"""歡迎使用 Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#多門選擇問題機率計算

import random

#計算條件
n = int(input("門數："))
cal = int(input("計算次數："))
win,lose = 0,0

for i in range(cal):
  #準備門
  #0代表沒車，1代表有車
  door = [0] * (n-1)
  idx = random.randint(0,len(door)-1)
  door.insert(idx,1)
  #隨機選一個門
  idx2 = random.randint(0,len(door)-1)
  #print(f"選到的門：{door[idx2]}")
  #依論參加者必須換門
  door.pop(idx2)
  #print(f"剩下的門：{door}")
  #主持人將協助排除1個無車之門
  door.remove(0)
  #print(f"剩下的門：{door}")
  #參加者再選一門
  idx3 = random.randint(0,len(door)-1)
  if door[idx3] == 1:
    win+=1
    #print("有車！")
  else:
    lose+=1
    #print("沒車！")

print(f"贏車的機率：{win/cal}")