# -*- coding: utf-8 -*-
"""歡迎使用 Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#大樂透選號

import random

#選號
def choose_num():
  print('選號規則：從1-49選擇6個號碼，號碼不足將自動電腦選號。')
  nums = input(f'請輸入你要選的號碼，並以空白鍵分隔：').split()
  number = []
  #擷取個人選擇號碼，檢查號碼是否超過範圍
  for num in nums:
    num = int(num)
    if num>49 or num<1:
      print(f'號碼{num}超出號碼範圍，已自動刪除')
    else:
      number.append(num)
  return(number)

#檢查號碼
def check_num(number:list)->list:
  #是否超過6個號碼
  if len(number)>6:
    number = number[:6]
    print(f'您選號已超過6個，已將{len(number)-6}個號碼移除!')
    return(number)
  #是否不足6個號碼
  elif len(number) < 6:
    count = 0
    while len(number) < 6:
      x = random.randint(1,49)
      if x not in number:
        number.append(x)
        count += 1
    print(f'您選號不足6個，已為您新增{count}個號碼!')
    return(number)
  else:
    return(number)

#列印號碼
def print_num(number:list)->list:
  #排序
  number.sort()
  print(f'您的樂透號碼為：{number}')
  print('---'*10)

#開獎
def open_num():
  result = []
  while len(result) < 7:
    x = random.randint(1,49)
    if x not in result:
      result.append(x)
  special = result.pop()
  result.sort()
  return(result,special)

#兌獎
def prize(number:list,result:list,special:int)->str:
  #核對選號有無對中特別號
  special_check = 0
  if special in number:
      special_check = 1
  #核對選號與開獎號中獎號碼
  number_set = set(number)
  result_set = set(result)
  winning_num = number_set.intersection(result_set)#交集
  winning_count = len(winning_num)

  if winning_count == 6:
    return('恭喜您種了頭獎!!')
  elif winning_count == 5 and special_check == 1:
    return('恭喜您種了貳獎!!')
  elif winning_count == 5:
    return('恭喜您種了參獎!!')
  elif winning_count == 4 and special_check == 1:
    return('恭喜您種了肆獎!!')
  elif winning_count == 4:
    return('恭喜您種了伍獎!!')
  elif winning_count == 3 and special_check == 1:
    return('恭喜您種了陸獎!!')
  elif winning_count == 2 and special_check == 1:
    return('恭喜您種了柒獎!!')
  elif winning_count == 3:
    return('恭喜您種了普獎!!')
  else:
    return('很可惜，您未中獎。請再接再厲!')

def main():
  number = choose_num()
  number = check_num(number)
  print_num(number)
  result,special = open_num()
  print(f'開獎號碼為：{result}，特別號為：{special}')
  print('---'*10)
  lottery_result = prize(number,result,special)
  print(lottery_result)

main()