# -*- coding: utf-8 -*-
"""猜數字遊戲

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v6vc36C9CxfXZMXronxGEFb6JOC_90Ge
"""

import random

low,heigh = 1,100
ans = random.randint(low,heigh)

while True:
  guess = int(input(f'請輸入你要猜的整數，範圍{low}-{heigh}: '))
  if guess > low and guess < heigh:
    if guess == ans:
      print(f'恭喜你猜中了！答案就是{ans}')
      break
    if guess < ans:
      low = guess
      print(f'猜錯了!再大一點!')
    else:
      heigh = guess
      print(f'猜錯了!再小一點!')
  else:
    print('不合理的數字')