# -*- coding: utf-8 -*-
"""歡迎使用 Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#剪刀石頭布
import random

#設定拳種
my_pose = int(input('請輸入你要出拳的數字:0.剪刀 1.石頭 2.布  '))
computer = random.randint(0,2)
trans = ['剪刀','石頭','布']

print(f'我出的拳:{trans[my_pose]}')
print(f'電腦出的拳:{trans[computer]}')

#判斷輸贏
if my_pose == (computer + 1) %3:
    print('你贏了')
elif my_pose == (computer -1) %3:
    print('你輸了')
else:
    print('平手')

#棒打老虎雞吃蟲
import random

#設定拳種
my_pose = int(input('請輸入你要出拳的數字:0.棒子 1.蟲 2.雞 3.老虎  '))
computer = random.randint(0,3)
trans = ['棒子','蟲','雞','老虎']

print(f'我出的拳:{trans[my_pose]}')
print(f'電腦出的拳:{trans[computer]}')

#判斷輸贏
if my_pose == (computer + 1) %4:
    print('你贏了')
elif my_pose == (computer -1) %4:
    print('你輸了')
else:
    print('平手')