# -*- coding: utf-8 -*-
"""歡迎使用 Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#印出左偏三角形
i = 0
while i < 10 :
  print('*'*(i+1))
  i += 1

#印出右偏三角形
left,right = ' ','x'
layer = 10
i = 0

while i < layer :
  rcount = i+1
  lcount = layer-i-1
  print(left * lcount + right * rcount)
  i += 1

#印出右偏倒三角形
left,right = ' ','x'
layer = 10
i = 0

while i < layer :
  rcount = layer-i
  lcount = i
  print(left * lcount + right * rcount)
  i += 1

#印出中間倒三角形
left,middle,right = ' ','o',' '
layer = 6
i = 0

while i < layer :
  rcount = i
  lcount = i
  mcount = (layer * 2 - 1) - i * 2
  print(left * lcount + middle * mcount + right * rcount)
  i += 1

#